[package]
name = "yt-observer"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories-next = "2.0.0"
iced = { version = "0.12", features = ["debug", "canvas"] }
tokio = "1.37.0"
